- name: Test clusters
  hosts: localhost
  tasks:

    - name: Get a list of clusters with hosts
      clusters:
        action: list
        with_hosts: true
      register: list_clusters

    - name: List clusters with hosts
      ansible.builtin.debug:
        var: list_clusters

    - name: Delete a cluster
      clusters:
        action: delete
        cluster_id: "{{ my_cluster_id }}"
      register: delete_cluster
      when: my_cluster_id is defined

    - name: List deleted cluster
      ansible.builtin.debug:
        var: delete_cluster
      when: delete_cluster is defined

    - name: Retrieve a cluster
      vars:
      clusters:
        action: get
        with_hosts: true
        cluster_id: 1ac5ec14-dc29-4c34-8013-29f8de0ccc00
      register: get_cluster

    - name: List cluster details
      ansible.builtin.debug:
        var: get_cluster
