- name: Test features
  hosts: localhost
  tasks:
    - name: Query OpenShift features
      features:
        openshift_version: 4.16.19
        cpu_architecture: x86_64
        platform_type: baremetal
      register: features_result

    - name: Print supported features
      debug:
        var: features_result
