- name: List supported operators
  hosts: localhost
  tasks:
    - name: List supported operators
      supported_operators:
      register: supported_operators

    - name: Print listed supported operators
      ansible.builtin.debug:
        var: supported_operators
